### ISSUE TITLE
AttributeError: module 'os' has no attribute 'sysconf'

### ISSUE THREAD

**Issue by TalibDaryabi** [HongyuHe/energat#3]
the line number 60 in common.py file raises an error for my system and says "os has no attribute 'sysconf'"
"""Number of clock ticks per second."""
CLK_TCK_PER_SEC: int = os.sysconf(os.sysconf_names["SC_CLK_TCK"])

  File "D:\Job\Expermient\AI_tools_to_track_the_emission\venv\lib\site-packages\energat\common.py", line 60, in <module>
    CLK_TCK_PER_SEC: int = os.sysconf(os.sysconf_names["SC_CLK_TCK"])
AttributeError: module 'os' has no attribute'sysconf''

I have installed Python 3.10 on my system.

**Comment by HongyuHe** [comment]
Hi @DaryabiTB, it appears that you are testing on a Windows machine. Unfortunately, energat currently only supports Linux.

**Comment by HongyuHe** [comment]
Feel free to reopen the issue if you have further questions! @DaryabiTB
